from apps.generic.choices import BaseChoices


class EmailType(BaseChoices):
    EMAIL_VERIFICATION_SUBJECT = "EMAIL_VERIFICATION_SUBJECT"
    EMAIL_VERIFICATION_BODY = "EMAIL_VERIFICATION_BODY"
    EMAIL_RESET_PASSWORD_SUBJECT = "EMAIL_RESET_PASSWORD_SUBJECT"
    EMAIL_RESET_PASSWORD_BODY = "EMAIL_RESET_PASSWORD_BODY"
